<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('files', function (Blueprint $table) {
            $table->id();

            $table->foreignId('user_id')
                ->constrained('users')
                ->cascadeOnDelete();

            $table->foreignId('conversation_id')
                ->nullable()
                ->constrained('conversations')
                ->nullOnDelete();

            /*
             * Original file name uploaded by the user.
             */
            $table->string('original_name');

            /*
             * Storage path generated by Laravel.
             *
             * Example:
             * users/5/files/abc123.pdf
             */
            $table->string('path');

            /*
             * Storage disk.
             *
             * Example:
             * local
             * public
             * s3
             */
            $table->string('disk')
                ->default('local');

            /*
             * MIME type.
             *
             * Example:
             * application/pdf
             * text/plain
             */
            $table->string('mime_type')
                ->nullable();

            /*
             * File extension.
             *
             * Example:
             * pdf
             * txt
             * docx
             */
            $table->string('extension', 20)
                ->nullable();

            /*
             * File size in bytes.
             */
            $table->unsignedBigInteger('size');

            /*
             * Current processing status.
             *
             * uploaded:
             * file saved but not processed yet
             *
             * processing:
             * extracting content
             *
             * processed:
             * ready to use with AI
             *
             * failed:
             * processing failed
             */
            $table->enum('status', [
                'uploaded',
                'processing',
                'processed',
                'failed',
            ])->default('uploaded');

            /*
             * Extracted textual content.
             *
             * Nullable because not every file has
             * been processed yet.
             */
            $table->longText('extracted_text')
                ->nullable();

            /*
             * Optional processing error.
             */
            $table->text('processing_error')
                ->nullable();

            $table->timestamps();

            $table->index([
                'user_id',
                'conversation_id',
            ]);

            $table->index('status');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('files');
    }
};
